rabbitmq:
  image : rabbitmq:3-management
  container_name: rabbitmq
  hostname: rabbitmq
  ports:
    - "15672:15672"
  expose:
    - "5672"
    - "4369"
    - "25672"
mongodb:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"
registryserver:
  image: vineet/registry-server
  container_name: registryserver
  ports:
   - "12871:12871"
  environment:
     SPRING_PROFILES_ACTIVE: cloud
gateway:
  image: vineet/gateway
  ports:
   - "10000:10000"
  links:
   - registryserver
   - bookregistrationservice
   - bookregistrationmessagebroker
   - bookregistrationweb
   - bookregistrationorder
   - bookrorderweb
  environment:
     SPRING_PROFILES_ACTIVE: cloud
bookregistrationservice:
  image: vineet/book-registration-service
  links:
   - registryserver
   - rabbitmq
   - mongodb
  environment:
     SPRING_PROFILES_ACTIVE: cloud
bookregistrationorder:
  image: vineet/book-registration-order
  links:
   - registryserver
   - rabbitmq
   - mongodb
  environment:
      SPRING_PROFILES_ACTIVE: cloud
bookregistrationmessagebroker:
  image: vineet/book-registration-message-broker
  links:
   - registryserver
   - rabbitmq
  environment:
      SPRING_PROFILES_ACTIVE: cloud
bookregistrationweb:
  image: vineet/book-service-web
  ports:
     - "9006:9006"
  links:
   - registryserver
  environment:
      SPRING_PROFILES_ACTIVE: cloud
bookrorderweb:
   image: vineet/book-order-web
   ports:
      - "9870:9870"
   links:
    - registryserver
   environment:
      SPRING_PROFILES_ACTIVE: cloud