rabbitmq:
  image : rabbitmq:3-management
  container_name: rabbitmq
  hostname: rabbitmq
  ports:
    - "15672:15672"
  expose:
    - "5672"
    - "4369"
    - "25672"
registryserver:
  image: vineet/registry-server
  ports:
   - "12871:12871"
  environment:
     SPRING_PROFILES_ACTIVE: cloud
gateway:
  image: vineet/gateway
  ports:
   - "10000:10000"
  links:
   - registryserver
   - bookregistrationservice
   - bookregistrationmessagebroker
   - bookregistrationweb
   - bookregistrationorder
  environment:
     SPRING_PROFILES_ACTIVE: cloud
bookregistrationservice:
  image: vineet/book-registration-service
  links:
   - registryserver
  environment:
     SPRING_PROFILES_ACTIVE: cloud
bookregistrationorder:
  image: vineet/book-registration-order
  links:
   - registryserver
   - rabbitmq
  environment:
      SPRING_PROFILES_ACTIVE: cloud
bookregistrationmessagebroker:
  image: vineet/book-registration-message-broker
  links:
   - registryserver
   - rabbitmq
  environment:
      SPRING_PROFILES_ACTIVE: cloud
bookregistrationweb:
  image: vineet/book-service-web
  ports:
     - "9006:9006"
  links:
   - registryserver
  environment:
      SPRING_PROFILES_ACTIVE: cloud